// vi:nu:et:sts=4 ts=4 sw=4
/* 
 * File:   pplex_internal.h
 *	Generated by Vogel 05/25/2015 23:36:46
 *
 * Notes:
 *   1	Before including define the following to customize the config bits for
 *		the development environment needed:
 *		_EXPLORER_16		Microchip Explorer 16 board
 *		_MAX32              Diligent MAX 32 board
 *		_NETWORK_SHIELD     Diligent Network Shield
 *
 * Created on September 26, 2014, 3:39 PM
 */

/*
 This is free and unencumbered software released into the public domain.
 
 Anyone is free to copy, modify, publish, use, compile, sell, or
 distribute this software, either in source code form or as a compiled
 binary, for any purpose, commercial or non-commercial, and by any
 means.
 
 In jurisdictions that recognize copyright laws, the author or authors
 of this software dedicate any and all copyright interest in the
 software to the public domain. We make this dedication for the benefit
 of the public at large and to the detriment of our heirs and
 successors. We intend this dedication to be an overt act of
 relinquishment in perpetuity of all present and future rights to this
 software under copyright law.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 
 For more information, please refer to <http://unlicense.org/>
 */




#ifndef PPLEX2_INTERNAL_H
#define	PPLEX2_INTERNAL_H


#include        <pplex2.h>
#include        <ObjArray.h>
#include        <ascii.h>
#include        <srcFiles.h>
#include        <Lex_internal.h>
#include        <Token_internal.h>
#include        <stdio.h>


#ifdef	__cplusplus
extern "C" {
#endif

    
#pragma pack(push, 1)
struct pplex2_data_s	{
    /* Warning - OBJ_DATA must be first in this object!
     */
    LEX_DATA        super;
    OBJ_IUNKNOWN    *pSuperVtbl;      // Needed for Inheritance

    uint16_t        kwdSel;         // Kewword Class Selection
    bool            fComments;      // TRUE == Include Comments in Token Stream

    bool            fTrace;
    
};
#pragma pack(pop)

    extern
    const
    PPLEX2_VTBL     pplex2_Vtbl;



    // Internal Functions
    uint32_t        pplex2_getFlags(
        PPLEX2_DATA     *this
    );

    bool            pplex2_setFlags(
        PPLEX2_DATA     *this,
        uint32_t        value
    );


    void            pplex2_Dealloc(
        OBJ_ID          objId
    );


    bool            pplex2_ParseToken(
        PPLEX2_DATA     *this,
        TOKEN_DATA      *pTokenOut          // Optional Output Token
    );

    
    bool            pplex2_ParseWhiteSpace(
        PPLEX2_DATA     *this
    );

    
    void *          pplex2_QueryInfo(
        OBJ_ID          objId,
        uint32_t        type,
        void            *pData
    );
    
    
    W32STR_DATA *   pplex2_SaveText(
        PPLEX2_DATA     *this,
        int32_t         terminatorChar1,    // '%' or '.'
        int32_t         terminatorChar2     // '>' or '}' or ']' or ')'
    );
    
    
#ifdef NDEBUG
#else
    bool			pplex2_Validate(
        PPLEX2_DATA     *this
    );
#endif



#ifdef	__cplusplus
}
#endif

#endif	/* PPLEX2_INTERNAL_H */

